spring:
    application:
        name: eureka-server

server:
    port: 9988

eureka:
    server:
        enable-self-preservation: true
    client:
        register-with-eureka: false
        fetch-registry: false
