GET http://localhost:8080/javierusechea-jsebastiangaleano-santiagoguerrerod/myservice/nombre/javierusechea

GET http://localhost:8080/javierusechea-jsebastiangaleano-santiagoguerrerod/myservice/nombre/jsebastiangaleano

GET http://localhost:8080/javierusechea-jsebastiangaleano-santiagoguerrerod/myservice/nombre/santiagoguerrerod